version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        networks:
            - learning
        volumes:
            # Mount source-code for development
            - ./:/var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway

    mysql:
        image: mysql:latest
        restart: always
        networks:
            - learning
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        ports:
            - "3305:3306"
        volumes:
            - mysql-volume:/var/lib/mysql

    pgsql:
        image: postgres:14.11-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5431:5432"
        networks:
            - learning
        volumes:
            - pgsql-volume:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        restart: always
        ports:
            - "6378:6379"
        networks:
            - learning
        volumes:
            - redis-volume:/data

networks:
    learning:
        driver: bridge

volumes:
    mysql-volume:
    pgsql-volume:
    redis-volume:
